# Build
FROM node:alpine as build

WORKDIR /app

COPY . ./

RUN npx lerna bootstrap

WORKDIR /app/apps/client

RUN yarn build

# Production
FROM nginx:stable-alpine

COPY --from=build /app/apps/client/build /usr/share/nginx/html
# COPY default.conf.template /etc/nginx/conf.d/default.conf.template
# COPY nginx.conf /etc/nginx/nginx.conf

CMD /bin/sh -c "envsubst '\$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf" && nginx -g 'daemon off;'
