FROM node:alpine

WORKDIR /app

COPY . ./

RUN npx lerna bootstrap

RUN yarn lerna run build --scope=@guillermocorrea/express-common --stream
RUN yarn lerna run build --scope=movies-service --stream

EXPOSE 4200

EXPOSE $PORT

WORKDIR /app/apps/movies-service

CMD ["yarn", "start"]
