# Build
FROM node:alpine as build

WORKDIR /app

COPY . ./

RUN npx lerna bootstrap

WORKDIR /app/apps/client

RUN yarn build

# Production
FROM nginx:stable-alpine
COPY --from=build /app/apps/client/build /usr/share/nginx/html
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
