name: Deploy to Heroku (Movies GraphQL endpoint)

on:
  push:
    branches:
      - master
    paths:
      - "apps/movies-service/**"
      - "packages/**"
      - ".github/workflows/movies-graphql.yml"
jobs:
  push_movies_client_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push Movies Service to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          context: .
          file: ./Dockerfile.movies-service.prod
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/movies-web-service:latest
