name: Deploy to Heroku (Movies Web Client)

on:
  push:
    branches:
      - master
    paths:
      - "apps/client/**"
      - "packages/**"
      - ".github/workflows/movies-client.yml"

jobs:
  push_movies_client_to_registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Push Movies Client to Docker Hub
        uses: docker/build-push-action@v2
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_PASSWORD}}
          context: .
          file: ./Dockerfile.movies-client.prod
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/movies-web-client:latest


      # - name: Login to Heroku Container Registry
      #   env:
      #     HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      #   run: heroku container:login
      # - name: Build and push
      #   env:
      #     HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      #   run: HEROKU_MOVIES_CLIENT_APP