name: Deploy to Heroku (Movies Web Client)

on:
  push:
    branches:
      - master
    paths:
      - "apps/client/**"
      - "packages/**"
      - ".github/workflows/movies-client.yml"

jobs:
  push_movies_client_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - uses: actions/checkout@v2
      - name: Push Movies Client to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile.movies-client.prod
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/movies-web-client:latest
      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: heroku container:login
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_TOKEN }}
        run: |
          docker pull guillermocorrea/movies-web-client
          docker tag guillermocorrea/movies-web-client:latest registry.heroku.com/${{ secrets.HEROKU_MOVIES_CLIENT_APP }}/web
          docker push registry.heroku.com/${{ secrets.HEROKU_MOVIES_CLIENT_APP }}/web
          heroku container:push web