name: Deploy to Heroku (Movies Web Client)

on:
  push:
    branches:
      - master
    paths:
      - "apps/client/**"
      - "packages/**"
      - ".github/workflows/movies-client.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install
        run: yarn install && yarn lerna bootstrap
      - name: Add backend remote origin
        run: git remote add heroku-movies-backend https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/${{ secrets.HEROKU_MOVIES_CLIENT_APP }}.git
      - name: Deploy backend to Heroku
        run: git push heroku-movies-backend `git subtree split --prefix apps/client master`:refs/heads/master --force